### ISSUE TITLE
기능 명세

### ISSUE THREAD

**Issue by captain-yun** [hyunayeo/memo_re#10]
### 최종결과물 : https://docs.google.com/spreadsheets/d/1rMhvBzNGAbKQU5zczINKqN6jWWbMprO6NVxWzuij_ss/edit?usp=sharing

* [기능명세서 작성법](https://velog.io/@osohyun0224/%ED%94%84%EB%A1%A0%ED%8A%B8-%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8%EC%84%9C-%EC%9E%91%EC%84%B1%ED%95%98%EB%8A%94-%EB%B2%95
)
* [리노 메모](http://linoit.com/users/picnic935/canvases/book%20memo.re)
* [플로우차트 작성법](https://velog.io/@osohyun0224/%ED%94%84%EB%A1%A0%ED%8A%B8-%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98-PM-%EA%B2%BD%ED%97%98%EA%B8%B0-1-IA-Flow-Chart-%EC%9E%91%EC%84%B1%EB%B2%95)

**Comment by hyunayeo** [comment]
https://docs.google.com/spreadsheets/d/1rMhvBzNGAbKQU5zczINKqN6jWWbMprO6NVxWzuij_ss/edit?usp=sharing

**Comment by devnabi** [comment]
- [x] Google Spreadsheets에서 SQL쿼리 작성 : MySQL workbench에서 가데이터를 넣었던 테이블로 필요한 데이터 가져와보고 Spreadsheets에 정리

**Comment by Lyrics109** [comment]
- 추가 기능 정리
- 기능별 sql 정리
