### ISSUE TITLE
개발환경 및 Git 세팅

### ISSUE THREAD

**Issue by devnabi** [hyunayeo/memo_re#11]
#### TODO
- [x] 깃 클론 https://github.com/hyunayeo/memo_re
- [x] #15
  - **dummy 브랜치** 만들기
![Image](https://github.com/hyunayeo/memo_re/assets/24825985/5907a1b1-65c2-498f-9f53-2ee9ad808818)
  - gitflow 메뉴에서 아래와 같이 설정
![Image](https://github.com/hyunayeo/memo_re/assets/24825985/64f605e1-c676-49cb-9a30-aa0f91af2ead)

#### 참고자료
- [GIT 브랜치 전략 세우기](https://inpa.tistory.com/entry/GIT-%E2%9A%A1%EF%B8%8F-%EA%B9%83%ED%97%99-PRPull-Request-%EB%B3%B4%EB%82%B4%EB%8A%94-%EB%B0%A9%EB%B2%95-folk-issue?category=890999)
- [Learn Git Branching - 게임으로 배우는 Git](https://learngitbranching.js.org/?locale=ko)

**Comment by captain-yun** [comment]
개발환경 세팅 완료 깃 브랜치 전략에 맞게 clone하여 개발 착수

**Comment by captain-yun** [comment]
### 깃 브랜치 전략 : github flow
- main 기준으로 브랜치를 분기해서 각자 기능별 개발
  - 예시 브랜치명 : feature/#4-api-test-using-mybatis
- 개발이 완료되면 main으로 pull request
- merge 되면 main에 합쳐지고 기존 작업하던 브랜치는 삭제하기

**Comment by captain-yun** [comment]
- [x] pull request 요청 시 자동 머지되는 문제 해결

**Comment by hyunayeo** [comment]
## 브랜치 설명
* main - master로 사용하는 브랜치
* feature/ - 기능 개발하여 main으로 merge 하는 브랜치

## 규칙
* main 으로 merge 할 때는 pull request를 생성하여 1명 이상의 approval을 받아야 한다.
* main 으로 pull request는 하루에 2~3회 내외로 한다.
