### ISSUE TITLE
MyBatis 연동

### ISSUE THREAD

**Issue by hyunayeo** [hyunayeo/memo_re#17]
- [x] Mybatis 라이브러리(디펜던시) 가져오기
- [x] DB와 연결 확인
- [x] 테스트 쿼리 작성 (CRUD)

**Comment by devnabi** [comment]
build gradle에서 디펜던시 추가 -> Mybatis, Lombok
Security는 나중에 추가

**Comment by devnabi** [comment]
- 참고 자료
[[MyBatis] Spring Boot Gradle 에 MySQL 연동하기](https://8ugust-dev.tistory.com/33)
[MyBatis 한솔 참고](https://devkuka.tistory.com/242)

**Comment by captain-yun** [comment]
### 스프링부트 + Mybatis 연동 (테스트를 위한 가장 심플한 방법!!!)
1. build.gradle - dependencies 에 다음 추가
  + implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.3'
2. 테이블과 매핑되는 엔티티 객체를 만들어준다.
![image](https://github.com/hyunayeo/memo_re/assets/24825985/94a53b30-ec13-4988-8ce6-a071871d5c7f)
3. 테이블과 엔티티 사이를 매핑해줄 mapper 클래스를 만든다.
![image](https://github.com/hyunayeo/memo_re/assets/24825985/58764cc4-a41d-4bd6-82db-aa76f57632d1)
4. 컨트롤러에 mapper 클래스 autowired로 의존성 주입
5. 매핑 url 지정 및 요청과 응답 로직 구현
![image](https://github.com/hyunayeo/memo_re/assets/24825985/d7ce0e26-ccb3-43ed-b9d3-7269d6907b17)
6. localhost:8080/api/members/5 로 테스트

[참고] https://medium.com/ryanjang-devnotes/spring-connect-spring-boot-to-db-with-mybatis-de6f82d12a26

**Comment by captain-yun** [comment]
## application.properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/book_memo_re?
&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
logging.level.com.zaxxer.hikari=TRACE
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

**Comment by captain-yun** [comment]
### [참고자료]
https://velog.io/@ygreenb/DTO-VO-Entity
+ dto는 gettet setter만 존재한다 setter를 없에고 생성자나 빌더패턴을 활용해 불변객체로 만들어 데이터의 안전성을 보존하는 방법도 있다
+ Entity는 DB의 테이블에 매핑되는 중요한 객체라 함부로 변경할 수 없기 때문에 DTO로 사용하기 부적절하다
+ VO는 getter만 존재하고 값은 생성자로 정의함 DTO와 달리 로직을 넣을 수 있다

**Comment by Lyrics109** [comment]
문제1 : application 동작 error 
해결 : MyBatisConfig 파일 삭제, .xml 파일 삭제
이유 : 환경설정 파일이 꼬인 것으로 추정

문제2 : white label 401, 500 에러
해결 : static index.html 추가 , properties .xml 삭제, localhost : 192.~~ 변경

**Comment by hyunayeo** [comment]
## test 실행 오류 해결
### 에러 1 

![image](https://github.com/hyunayeo/memo_re/assets/48472568/73f4eb4e-5254-4d1d-83fe-5d12b1fc808c)

* intellij setting 에서  gradle run test using 변경 (Gradle -> intelliJ IDEA)
![image](https://github.com/hyunayeo/memo_re/assets/48472568/3050f2a5-7b78-4bd5-92e1-8b3c3e038bec)

### 에러 2

![image](https://github.com/hyunayeo/memo_re/assets/48472568/59ba78cb-9c70-4000-b92c-a3e958f2fee3)

* build.gradle 버전 변경
 testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
-> 버전 변경
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
