### ISSUE TITLE
화면 설계

### ISSUE THREAD

**Issue by captain-yun** [hyunayeo/memo_re#5]
**화면 설계도**
* [Excalidraw](https://excalidraw.com/#room=9f028980d4f84b09e6ba,IcBypt938AykAnkWtsH33Q)
* [Figma](https://www.figma.com/file/lDBbGxv289TGOAh1IYUoCc/Untitled?type=design&node-id=0-1&mode=design&t=SK46LNTfCuuU8W6f-0)

**Comment by devnabi** [comment]
- [x] DB설계하면서 빠진 것 찾아냄 -> 탈퇴버튼이 없었던 것을 만들고 탈퇴 화면을 구성했다.
(탈퇴버튼을 클릭 -> 회원의 비밀번호를 입력하는 화면 -> 탈퇴 성공화면)

**Comment by hyunayeo** [comment]
- [ ] nav bar 구성 보강
- [ ] profile 이미지 추가

**Comment by Lyrics109** [comment]
전체
- [ ] 전체적인 게시판 디자인과 메뉴 구성 통일
- [ ] 사용자 친화적인 화면 설계 (멘트 및 이동경로 수정)
- [ ] 인기글 = 조회수
- [ ] 모든 에러에 대한 에러 페이지 생성
- [ ] 도서와 게시판 검색 분리
- [ ] 검색바 ▼  전체 -> 도서(default), 게시판으로 수정

Book
- [ ] 사용자가 등록한 도서는 등록 및 수정만 가능/ 삭제는 관리자 한정

My home
- [ ] Wish, Reading, Done 게시판 병합
- [ ] MY HOME 버튼 -> Profile 이미지로 대체
- [ ] Profile 이미지 크기 조절 (figma 참고)

나의 기록
- [ ] 게시글 private 버튼으로 공개여부 결정 (완독 여부 무상관)
- [ ] 기록 페이지 수정/삭제 페이지 추가
- [ ] 찜목록은 비공개
- [ ] 그래프 상세페이지 월별, 연별 추가
- [ ] 카테고리 상세페이지 월별, 연별 추가

상대방 기록
- [ ] 프로필 들어갔을 때 상대방 public 글 목록
- [ ] 상대방 글 눌렀을 때 보여주는 화면

캘린더 
- [ ] 캘린더 표지 표시일 (default) = start_date
- [ ] 완료 꽃 표 = done 1
- [ ] 모든 계획 줄 하나로 표시함 (커서 올렸을 때 계획된 도서 목록 열람 가능)
- [ ] 독서 표지만 나온 페이지(default)와 독서 계획만 나온 페이지로 분할

- end_date 와 완독(done)은 서로 다름
- start_date와 end_date는 수정 가능

Wish
- [ ] wish 목록 개별화(나의 찜)
- [ ] wish 게시글 목록 추가
