### ISSUE TITLE
DB 설계 & 테이블 생성

### ISSUE THREAD

**Issue by captain-yun** [hyunayeo/memo_re#6]
**사용 도구**
* [diagrams](https://app.diagrams.net/)

**Comment by hyunayeo** [comment]
https://www.erdcloud.com/d/LqKyNdZqiY95yeemg

**Comment by captain-yun** [comment]
- [x]  가데이터 만들기 (FK 제약조건 고려해서 테이블 순서 생각하며 만들기)

[Dump20231120.zip](https://github.com/hyunayeo/memo_re/files/13406965/Dump20231120.zip)


- [x]  쿼리 날려보기 -> 수정사항 있는지 체크
- [x]  위키에 새로운 덤프 업데이트

**Comment by captain-yun** [comment]
- [x] 공용 DB 만들기 
※ [**사전에 접속 제한 해제하기**](https://1mini2.tistory.com/87)
> - 192.168.10.250
> - root / 1234

**Comment by captain-yun** [comment]
@Lyrics109 다했어요.. 검토좀 해주세요
@devnabi 쿼리좀 봐주세요

**Comment by captain-yun** [comment]
- [x] DB 테이블 book -> modified at 컬럼 추가

**Comment by Lyrics109** [comment]
DB 테이블 메타 정보 컬럼 추가
- [x]  member :  created_at, modified_at, deleted_at
- [x]  book : created_at, modified_at
- [x]  article : ccreated_at, modified_at, deleted_at

DB 테이블 컬럼명 변경
- [x]  article : finished_date  -> end_date

 DB 테이블 member, book, article 컬럼 순서 정렬

**Comment by Lyrics109** [comment]
DB 테이블 정보 컬럼 추가 (미적용)
- [ ] 자기소개 컬럼 추가 / member : info
- [ ] wish 상대방 게시글 컬럼 추가 / wish : ??

**Comment by hyunayeo** [comment]
article 테이블 컬럼명 변경
* private -> is_hide
