### ISSUE TITLE
API 설계

### ISSUE THREAD

**Issue by captain-yun** [hyunayeo/memo_re#8]
#### 참고자료
+ Spring에서 알라딘에서 받은 JSON 데이터 DB에 저장하기
[Spring->MySQL](https://velog.io/@pyoong/Spring-JSON-%EB%8D%B0%EC%9D%B4%ED%84%B0-mysql%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-%EC%95%8C%EB%9D%BC%EB%94%98-OpenAPI)
+ API 설계 원칙 (REST API 위주) 
  + https://velog.io/@msung99/RestFul-%ED%95%9C-API-%EC%9D%98-%EC%84%A4%EA%B3%84%EC%9B%90%EC%B9%99%EC%97%90-%EB%8C%80%ED%95%B4
  + https://appmaster.io/ko/blog/dijain-weoncigyi-hyusig
  + https://kmkunk.tistory.com/139
  + https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-4.-API-%EC%84%A4%EA%B3%84-%EC%9B%90%EC%B9%99%EA%B3%BC-%EC%A7%81%EB%A0%AC%ED%99%94-%ED%8F%AC%EB%A7%B7-%EA%B2%B0%EC%A0%95
  + https://prohannah.tistory.com/156

**Comment by hyunayeo** [comment]
[API 명세서](https://docs.google.com/spreadsheets/d/1rMhvBzNGAbKQU5zczINKqN6jWWbMprO6NVxWzuij_ss/edit?usp=sharing)

**Comment by Lyrics109** [comment]
[명세서 참고](https://seb.oopy.io/26660d97-e4e3-4bac-90e0-7ed483f71311)

- request.body(예제) 가 요청 변수 및 타입을 대체함
- 개발시 api 수정 (진행중)
